### PR TITLE
Updated & simplified sidebar action buttons

### LINKED ISSUE #158: Surface "publish" and "unpublish" functionality
Now that we have functions in this add-on to toggle an article's `published` status, we need to provide a way to trigger them. I suppose the most straightforward way is to offer two additional buttons: "publish" and "unpublish" - however, then we'd have quite a few buttons in the sidebar

Just wanted to log this issue that we (or just I) need to think through the UX of this fundamental functionality. 

For now, I'll make it so the publishing tools sidebar includes the following action buttons:

* Preview (saves data, no publish, returns link to view preview of article)
* Save (saves data, no publish)
* Publish (does not save data, does set `published: true` in article record)
* Unpublish (does not save data, does set `published: false` in article record)

### PR DESCRIPTION
**Pull request by jacqui**
Closes #158 

This PR updates the buttons in the sidebar to the following:

* Preview: same as before, this button saves the data in the db and returns a link to view
* Publish: saves the doc, sets `published: true`; this button is labelled "Re-publish" if the doc's been published already
* Unpublish: sets `published: false` on the article

Thanks for helping with the UX, @TylerFisher!

### CODE REVIEW

**Comment by TylerFisher** [comment]
Yeah, so this is a tricky UX thing to communicate: unlike something like WordPress, we actually don't need to "save" drafts because the Google Doc does that for you. The sidebar is purely for previewing/publishing. So mostly I think saying "save" is confusing. I don't think it does what most people think it will.

Given that, I think what we want are two buttons at all times:

1. Preview. You can always preview something.
2. Publish/republish. If the article has never been published, it does the normal publish thing. If it has been published before, it "saves" a new version and publishes that version.

If we've published before, we show an additional button: "Unpublish".

**Comment by jacqui** [comment]
Thanks for the feedback, that cleared things up for me.

I've made the changes to the API (deployed to oaklyn branch / https://djomoky4uky4c.cloudfront.net/graphql) and updated this PR so the buttons are:

* document hasn't been published: "preview"  and "publish"
* document has been published: "preview" "re-publish" and "unpublish"
* clicking "preview" behaves as before - it saves the doc, sets published: false, returns link
* clicking "publish" saves the doc, sets published: true
* clicking "re-publish" does the same as "publish"
* clicking "unpublish" sets "published: false"

**Comment by TylerFisher** [comment]
Okay I managed to test this by going back to the legacy editor. Republish worked as expected. When I tried to preview [my article](https://docs.google.com/document/d/113OlKvSL3pwaq2aHuerySt6iT68mmp55SF8iWc8vXjE/edit?addon_dry_run=AAnXSK-lISvEy4EqZIRyCUr_sQoknwNvJGig-fWigC2R7FSz868BVLJHeHSToSb0qgHDo2amCUGI2mWRJKUWgYn86-kj_vIVTdQAxfhq_Ry6zHQAK-O9zHDBMnfIiU1j3lviUAfzO2C2), the preview loaded the wrong article. Not sure why this is happening, the URL looks correct.

**Comment by TylerFisher** [comment]
It looks like this part of the code is working correctly. I think this is an issue on the frontend.

**Pull request merged**
